CasualGaming/studlan

- apps/team/views.py
> Add direct invitation accept/decline in inbox

- apps/team/views.py
- templates/team/team.html
> Exclude users invited to team from invitation dropdown

- .drone.yml
- Dockerfile
- docker-entrypoint.sh
* Changing the registry and host for deployment
* Bases the docker image on python:2.7.12 which is debian instead of alpine
> Change docker image

- apps/authentication/views.py
- Add empty lan variable to avoid reference before assignment bug
- Add exists check on query to avoid out of bounds bug
> Update direct register view in auth app. Fixes #143

- docker-entrypoint.sh
> fixes issue where docker-entrypoint uses wrong directory

- studlan/settings/base.py
> fixes issue with static path

- templates/base.html
Wrapps the needed links with "" to avoid extra characters
> Adds missed Quotation wraps after update

- apps/authentication/forms.py
- apps/authentication/views.py
- apps/misc/forms.py
- apps/team/forms.py
- apps/userprofile/forms.py
- Starts using add_error(), istead of old self._errors[''] = self.error_class(
- Adds ErrorList as Super to InlineSpanErrorList class
> Changes _errors to add_error because of changes in form error handling

- requirements/base.txt
- studlan/settings/base.py
- vagrantbootstrap.sh
Changes how markdown is handeling URLs
> Markdown url fix 169

- docker-entrypoint.sh
Attempt to fix POSTMAN migration error, now without deleting vagrantbootsrap.sh
> Attempt to fix postman migration error

- apps/news/views.py
No idea why it didn't crash untill now, have tested that feature, anyhow this should be a better solution
> Now fetches mulitple active lans

- requirements/base.txt
- studlan/settings/base.py
- studlan/settings/example-local.py
- studlan/settings/example-prod-local.py
> Sentry mathiafl

- requirements/base.txt
- studlan/settings/base.py
- studlan/settings/example-local.py
- studlan/settings/example-prod-local.py
Reverts CasualGaming/studlan#189
> Revert "Sentry mathiafl"

- .drone.yml
- CONTRIBUTORS
- MAINTAINERS
Use drone.casualgaming.no instead of drone.fap.no for CI and deployment.
- Deploys will no longer hit recess.no
- Only staging environment is deployed using Drone as of now
> Drone mario

- Dockerfile
> Bump Python from 2.7.12 to 2.7.15

- .gitignore
- apps/competition/views.py
- templates/competition/competition.html
> Fix bug that prevented participant from unregistering from a competition

- apps/authentication/forms.py
Fixes #226. Requires new passwords to be of length 8 or more.
- Add minimum length of 8 to passwords
> Add password minimum length check

- apps/authentication/forms.py
- apps/userprofile/templatetags/profile_tags.py
- apps/userprofile/urls.py
- apps/userprofile/views.py
- templates/404.html
- templates/500.html
- templates/sidebar.html
- templates/user/alias.html
- templates/user/history.html
- templates/user/inbox.html
- templates/user/profile.html
- templates/user/profile_content.html
- templates/user/profile_tabs.html
- templates/user/public_profile.html
- templates/user/update.html
- templates/userdropdown.html
Fixes #229. Replace "my profile" and public profile pages. Show a little more info, hide full name from the public, and inform the user about what info is public.
- Update private and public user profile pages and hide the full name in the public one
The full name is probably still disclosed to the public in other places.
> Update public profile

- Dockerfile
- apps/userprofile/admin.py
- manage/ci-analyze-source.sh
- manage/ci-test.sh
- manage/ci-validate-django.sh
- sample-configs/deploy-scripts/restore-db.sh
- studlan/settings/base.py
- templates/competition/competition.html
- templates/team/team.html
- uwsgi.ini
Minor things, see commits.
- Add error log file
- Fix broken URL path references
> Minor things

- apps/api/models.py
- apps/api/views.py
- apps/arrivals/views.py
- apps/authentication/views.py
- apps/competition/views.py
- apps/lan/views.py
- apps/team/models.py
- apps/userprofile/models.py
- studlan/settings/base.py
Fixes #233, probably.
- Fix string encoding error
> Fix string encoding

- templates/competition/competition.html
- templates/lan/details.html
Fix some static URLs in templates. It broke an image and therefore made the Stripe client script complain.
- Fix some static URLs in templates.
> Fix some static URLs in templates

- .travis.yml
Travis didn't trigger the release deployments because it doesn't know the branch for tags (which makes sense). Releases are now triggered without a branch restriction.
> Fix travis release condition

- CHANGELOG.md
Promote v1.3.13 to v1.4.0 instead (I changed my mind).
> Update changelog for release v1.4.0

- CHANGELOG.md
- templates/user/profile_content.html
Fixes wrong join and last login time on user profiles.
- Fixed wrong join and last login time on user profiles.
> Fix wrong join and last login time on user profiles

- CHANGELOG.md
- apps/userprofile/urls.py
- apps/userprofile/views.py
Fixes #246.
- Fixed internal error when accessing `/profile`.
- Prepared changelog for release.
> Fix internal error when accessing /profile

- apps/seating/management/commands/generatelayout.py
Fixes remaining code smells in [SonarCloud](https://sonarcloud.io/dashboard?id=CasualGaming_studlan).
> Fix code quality, part 2

- files/css/custom.css
- templates/sponsor/sponsors.html
- templates/sponsorbar.html
- Fix malformed sponsor image/title links due to an extra `</a>`.
- Add link from sponsorbar title to sponsor page.
> Fix sponsor links

- templates/payment/checkout.html
- templates/payment/info.html
Remove settings from payment templates.
- Remove settings from payment templates.
> Remove settings tag from payment templates

- templates/payment/checkout.html
Ensure that stripe public key is set in payment template
- Ensure that stripe public key is set in payment template
> Ensure that stripe public key is set in payment template

- apps/payment/views.py
The payment page checked if the user already had a ticket, but not if the user's "attendance" was marked as paid.
> Check if user has paid attendance on payment page

- apps/seating/views.py
- files/css/custom.css
- templates/competition/competitions.html
Bugfixes for bugs introduces by the PRs.
- Fix compo list DOM.
- Fix seating map error for anon users.
- Fix breadcrumb spacing. The reduction in top padding on small screens moved the breadcrumbs too far up, so it was reverted.
> Fix compo DOM and seating anon error

- apps/payment/views.py
Refactor a bit of code that was just too painful to look at. Has been tested with with errors using GET (user) and POST (Stripe) and without errors (GET and POST).
> Refactor some payment code

- CHANGELOG.md
See the changelog. Test relevant features.
> Prep for release 1.6.0

- requirements.txt
- requirements/all.txt
- requirements/development.txt
- requirements/production.txt
- requirements/test.txt
Upgrade deps. No big version changes.
-
-
-
-
-
> Upgrade deps

- Dockerfile
- README.md
- docs/deployment.md
- docs/development.md
- docs/docker-image.md
- docs/releasing.md
- manage/docker/setup.sh
- setup/docker-compose.dev.yml
- Updated docs. Formatting, mostly.
- Briefly optimized the Dockerfile: Aggregated a few Docker RUNs.
- Fixed a minor problem with the Docker dev setup.
> Minor doc and dev setup changes

- requirements.txt
- requirements/all.txt
- requirements/development.txt
- requirements/production.txt
- requirements/test.txt
Upgrade deps. No major changes. Minor changes include fixing a Django vuln.
> Upgrade deps to fix Django vuln

- CHANGELOG.md
- apps/lan/views.py
- templates/lan/details.html
Fixes attendance button CSRF on the LAN page. Cherry-picked from #338.
- Fixed LAN attendance CSRF vulnerability.
> Fix attendance CSRF

- apps/arrivals/views.py
- templates/arrivals/home.html
Fixes a crash on the arrivals page when there are no seat reservations.
> Fix arrivals error for no seats

- apps/sendmail/views.py
Attempt to fix error 500 for sending mail.
> Change sendmail recipient list builder slightly

- CHANGELOG.md
- apps/arrivals/views.py
- files/js/arrival.js
- locale/nb/LC_MESSAGES/django.po
- templates/arrivals/arrivals.html
Fixes #182.
- Added arrivals table filter for ticket/paid type.
Also fixes a misplaces changelog item.
> Add arrivals table filter for paid type

- .github/PULL_REQUEST_TEMPLATE.md
- CHANGELOG.md
- Dockerfile
- apps/authentication/views.py
- apps/userprofile/admin.py
- files/css/custom.css
- locale/nb/LC_MESSAGES/django.po
- templates/common/lan_list.html
- templates/news/news.html
- templates/userdropdown.html
Collection of miscellaneus stuff.
- Optimize Dockerfile.
- Fix login and logout next redirect.
- Update PR template.
- Make front page LAN header clickable.
- Fix previous LAN list order.
- Add user admin filter for users with custom permissions.
> Miscellanea

- CHANGELOG.md
- requirements.txt
- requirements/all.txt
- requirements/development.txt
- requirements/production.txt
- requirements/test.in
- requirements/test.txt
Upgrade deps to fix certain secutiry vulnerabilities.
- Upgrade deps.
- Remove flake8-bandit (only installed when testing).
> Upgrade deps to fix vulns

- CHANGELOG.md
- apps/lan/views.py
- Add missing ticket purchase date to Excel export
> Add missing ticket purchase date to Excel export

- docs/development.md
- manage/venv/activate-venv.sh
> Update dev docs and venv script

- apps/competition/models.py
- apps/competition/views.py
- apps/sendmail/forms.py
- apps/sendmail/management/commands/sendmail.py
- apps/sendmail/views.py
- manage/venv/make-translations.sh
- templates/competition/competition.html
- templates/competition/competition_user_table.html
- templates/competition/competitions.html
> Fix sendmail receiver deduplication and stuff

- .dockerignore
- apps/sendmail/views.py
> Fix sendmail duplicate receivers

- CHANGELOG.md
- apps/statistics/views.py
- locale/nb/LC_MESSAGES/django.po
- requirements.txt
- requirements/all.txt
- requirements/development.txt
- requirements/production.txt
- requirements/test.txt
- templates/lan/tickets.html
- templates/statistics/lan.html
- Added cumulative age counts in statistics page.
- Allow Markdown in ticket descriptions on the ticket page.
- Fixed typo in statistics page permission, preventing non-superusers from accessing it.
(If apropriate.)
> Enhance stats and tickets and upgrade deps

- CHANGELOG.md
- apps/misc/templatetags/misc.py
- apps/payment/views.py
- files/css/custom.css
- files/js/arrival.js
- files/js/payment.js
- locale/nb/LC_MESSAGES/django.po
- templates/arrivals/arrivals.html
- templates/arrivals/toggle_icons.html
- templates/payment/checkout.html
- Added error icon and message on the arrivals page for users without an associated attendee object.
- Replaced email address with age on the arrivals page.
- Make failed ticket purchases reload the purchase page and successful purchases redirect to the seatmap page.
(If apropriate.)
> Update arrivals page and ticket purchase redirects
